[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' https://images.unsplash.com https://ui-avatars.com data:;
      script-src 'self';
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
      connect-src 'self';
      frame-src https://docs.google.com;
      base-uri 'self';
      form-action 'self' https://docs.google.com;
    """
